[package]
name = "iroh-ai-sandbox"
version = "0.1.0"
description = "A restricted-workspace desktop AI assistant"
authors = ["Mandeep Thapa"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "iroh_ai_sandbox_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sysinfo = "0.33"
chrono = "0.4"
tokio = { version = "1", features = ["full"] }
log = "0.4"
ignore = "0.4.31"
reqwest = { version = "0.13.4", features = ["json", "multipart"] }
lazy_static = "1.5.0"
scraper = "0.27.0"
urlencoding = "2.1.3"
pdf-extract = "0.12.0"
base64 = "0.22.1"
dotenvy = "0.15.7"
headless_chrome = { git = "https://github.com/rust-headless-chrome/rust-headless-chrome", features = ["fetch"] }
tauri-plugin-updater = "2.10.1"
tauri-plugin-process = "2.3.1"

[dependencies.windows]
version = "0.58.0"
features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Security_Authorization",
    "Win32_Security_Cryptography",
    "Win32_System_Threading",
    "Win32_System_Environment",
    "Win32_NetworkManagement_NetManagement",
    "Win32_System_Console",
    "Win32_System_Pipes"
]

